<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-RSD3KNP9" ignored="0" name="login feature and Verify details of Signed in User" tests="6" failures="1" timestamp="14 Jan 2018 17:19:09 GMT" time="143.021" errors="0">
  <testcase name="testPersonalInfoUI" time="11.593" classname="blablacarB13.tests.profile.personalInfo.VerifyPersonalInfoPageDetails"/>
  <testcase name="testUserDetailsOnForm" time="6.404" classname="blablacarB13.tests.profile.personalInfo.VerifyDifferentUserCreation"/>
  <testcase name="testUserDetailsOnForm" time="5.96" classname="blablacarB13.tests.profile.personalInfo.VerifyDifferentUserCreation">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Mobile Number is not as expected :  expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:Mobile Number is not as expected :  expected [true] but found [false]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at blablacarB13.tests.profile.personalInfo.VerifyDifferentUserCreation.testUserDetailsOnForm(VerifyDifferentUserCreation.java:78)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.TestNG.privateMain(TestNG.java:1330)at org.testng.TestNG.main(TestNG.java:1299)]]>
    </failure>
  </testcase> <!-- testUserDetailsOnForm -->
  <testcase name="logInwithFacebookValidDetails" time="6.836" classname="blablacarB13.tests.common.LoginFeature"/>
  <testcase name="logInwithUserDetails" time="4.212" classname="blablacarB13.tests.common.LoginFeature"/>
  <testcase name="logInwithFacebookInvalidDetails" time="5.046" classname="blablacarB13.tests.common.LoginFeature"/>
</testsuite> <!-- login feature and Verify details of Signed in User -->
